itsyouonline/identityserver

db/constants.go, db/init.go, db/middleware.go, db/session.go, http/resource.go, http/route.go, identityservice/service.go, identityservice/user/api/users.go, identityservice/user/models/constants.go, identityservice/user/models/init.go, identityservice/user/models/user.go, identityservice/user/routes.go, main.go, oauthservice/service.go, routes/logger.go, routes/router.go, routes/routes.go, siteservice/service.go
+ Structure
+ Resources, DB & routing abstraction implementation
+ User model & API
=> User API implementation

db/model.go, identityservice/company/api/companies.go, identityservice/company/models/company.go, identityservice/company/models/constants.go, identityservice/company/models/init.go, identityservice/company/routes.go, identityservice/service.go, identityservice/user/models/user.go, identityservice/user/routes.go
+ Company model and API
+ Ensure Indices are created
=> Implement company API

specifications/api/companies.raml, specifications/api/users.raml
=> Add PUT to raml specs

identityservice/company/api/companies.go, identityservice/user/api/users.go, specifications/api/companies.raml, specifications/api/users.raml
+ User username & Id are immutable
+ Company globalId & Id are immutable
=> Implement PUT in User and Company API

identityservice/user/user.go, identityservice/user/users_api.go, siteservice/registration.go, specifications/api/users.raml
+ Update specs based on go-raml support - Note: API workbench complains about current specs.
+ Update users API
=> Update specs and user info API

specifications/api/organizations.raml
+ Note: Sub-orgs are not yet finalized.
Suggested way to sub-orgs RESTful relations:
```json
POST /organizations/<parent-org>/suborganizations/
{
"globalid": "<child-org>"
}
// To remove Sub-org from parent org
DELETE /organizations/<parent-org>/suborganizations/<child-org>
```
=> Add organizations spec

.gitignore, Dockerfile-api-console, docker-compose.yml, docs/dist/index.html, docs/dist/style.css
+ Integrate with docker-compose
=> Add dockerfile for api-console

identityservice/user/Phonenumber.go, identityservice/user/db.go, identityservice/user/users_api.go, identityservice/user/users_if.go, specifications/api/users.raml
+ Bank handlers
+ Address handlers
+ Phone handlers
=> Extend Users API

siteservice/website/assets/css/style.css, siteservice/website/components/organization/controller.js, siteservice/website/components/organization/service.js, siteservice/website/components/organization/views/detail.html, siteservice/website/components/organization/views/invite.html, siteservice/website/home.html
+ Organization details
+ Invite page
=> Apply changes for organizations

db/middleware.go, db/session.go, identityservice/company/companies_api.go, identityservice/organization/organizations_api.go, identityservice/user/users_api.go, identityservice/userorganization/user_organizations_api.go
+ Close request db session
+ Make sure writing headers is done before writing response body
=> Fix DB session and write header issues

siteservice/website/components/organization/controller.js, siteservice/website/components/organization/views/new.html
=> Fix DNS not saved - solves #24

siteservice/website/assets/css/style.css, siteservice/website/authorize.html, siteservice/website/components/organization/views/new.html, siteservice/website/index.html, siteservice/website/login.html, siteservice/website/registration.html
=> Various responsive design fixes; closes #57

siteservice/oauth_callbacks.go
Also, ensure these 4 docs are present in the `globalconfig` collection:
key: github-clientid
value: <github client id>
key: github-secret
value: <github-secret>
key: facebook-clientid
value: <facebook app id>
key: facebook-secret
value: <facebook secret>
=> change hardcoded oauth callback

siteservice/website/components/user/authorizeController.js, siteservice/website/registration.html
+ support for non-ES6 browsers on authorize page
=> fix registration page layout

siteservice/website/assets/css/style.css, siteservice/website/authorize.html, siteservice/website/components/user/authorizeController.js, siteservice/website/logintotpform.html
Part of https://github.com/gig-projects/org_development/issues/134
=> ability to choose shared information

docs/oauth2/config.ini, docs/oauth2/jwt.md, docs/oauth2/oauth2.md, docs/oauth2/oauthtoken.py
Add a simple script which can be used to get oauth/jwt token with
specified scope.
=> Update docs and add simple script to get tokens

credentials/password/db.go, identityservice/user/users_api.go, identityservice/user/users_if.go, specifications/api/users.raml
Adds an API method on /users/{username}/password to update the password
=> Backend implementation for update password

DockerfileMinimal, db/user/apikey/db.go, db/user/apikey/model.go, db/user/db.go, identityservice/user/users_api.go, identityservice/user/users_if.go, oauthservice/access_token.go, specifications/api/users.raml
Add restapi for managing user apikeys.
- currently we use scope user:admin
Allow apikeys when requesting access_token
=> Add API keys per user.

credentials/password/db.go, identityservice/user/users_api.go, siteservice/registration.go, siteservice/website/assets/css/style.css, siteservice/website/components/company/views/detail.html, siteservice/website/components/organization/views/detail.html, siteservice/website/components/user/controller.js, siteservice/website/components/user/service.js, siteservice/website/components/user/views/home.html, siteservice/website/components/user/views/resetPasswordDialog.html, specifications/api/users.raml
Closes https://github.com/gig-projects/org_development/issues/230
=> Add change password UI

siteservice/website/smsconfirmation.html
Closes https://github.com/gig-projects/org_development/issues/242
=> Make the sms confirmation page mobile friendly

siteservice/registration.go, siteservice/service.go, siteservice/website/assets/css/style.css, siteservice/website/base.html, siteservice/website/components/app.js, siteservice/website/components/registration/registrationApp.js, siteservice/website/components/registration/registrationController.js, siteservice/website/components/registration/registrationResendSmsController.js, siteservice/website/components/registration/registrationService.js, siteservice/website/components/registration/registrationSmsController.js, siteservice/website/components/registration/views/registrationform.html, siteservice/website/components/shared/configService.js, siteservice/website/components/shared/shared.js, siteservice/website/registration.html
Probably closes https://github.com/gig-projects/org_development/issues/229
=> Improved and fixed registration procedure

db/user/Authorization.go, db/user/User.go, db/user/db.go, docs/oauth2/availableScopes.md, identityservice/user/users_api.go, identityservice/user/users_if.go, identityservice/user/userview.go, siteservice/authorize.go, siteservice/website/components/login/loginSmsController.js, siteservice/website/components/user/authorizeController.js, siteservice/website/components/user/controller.js, siteservice/website/components/user/directives/authorizationDetails.html, siteservice/website/components/user/service.js, siteservice/website/components/user/views/home.html, siteservice/website/components/user/views/nameDialog.html, specifications/api/users.raml
Also fixes authorization request page infinite loop
Closes https://github.com/gig-projects/org_development/issues/185
=> Add first name and last name to user information

identityservice/user/users_api.go, identityservice/user/users_if.go, siteservice/website/assets/css/style.css, siteservice/website/components/user/controller.js, siteservice/website/components/user/service.js, siteservice/website/components/user/views/home.html, siteservice/website/components/user/views/verifyPhoneDialog.html, specifications/api/users.raml, validation/phonenumber.go
Closes https://github.com/gig-projects/org_development/issues/186
Closes https://github.com/gig-projects/org_development/issues/227
=> Add phone number verification UI

siteservice/website/assets/css/style.css, siteservice/website/base.html, siteservice/website/components/app.js, siteservice/website/components/organization/views/detail.html, siteservice/website/components/shared/directives/footer.html, siteservice/website/components/shared/directives/footer.js, siteservice/website/components/user/views/home.html
Closes https://github.com/gig-projects/org_development/issues/249
=> Add footer to logged in pages

siteservice/website/components/login/loginController.js, siteservice/website/components/login/views/loginform.html, siteservice/website/login.html
Closes https://github.com/gig-projects/org_development/issues/250
=> Show the client id when logging in on the authorize page

db/user/db.go, siteservice/login.go, siteservice/registration.go, siteservice/service.go, siteservice/website/components/login/forgotPasswordController.js, siteservice/website/components/login/loginApp.js, siteservice/website/components/login/views/forgotpassword.html, siteservice/website/components/login/views/loginform.html, siteservice/website/login.html
Part of https://github.com/gig-projects/org_development/issues/190
Backend implementation still needs to be done
=> Forgot password UI

db/user/User.go, siteservice/registration.go, siteservice/website/components/app.js, siteservice/website/components/login/loginSmsController.js, siteservice/website/components/login/loginTotpController.js, siteservice/website/components/login/views/loginsmsform.html, siteservice/website/components/login/views/logintotpform.html, siteservice/website/components/organization/views/detail.html, siteservice/website/components/organization/views/new.html, siteservice/website/components/registration/registrationController.js, siteservice/website/components/registration/registrationResendSmsController.js, siteservice/website/components/registration/registrationService.js, siteservice/website/components/registration/registrationSmsController.js, siteservice/website/components/registration/views/registrationform.html, siteservice/website/components/registration/views/registrationresendsms.html, siteservice/website/components/user/controller.js, siteservice/website/components/user/views/verifyPhoneDialog.html
Closes https://github.com/gig-projects/org_development/issues/254
Closes #96
=> Username validation

siteservice/website/components/shared/directives/header.html, siteservice/website/components/user/controller.js
Closes https://github.com/gig-projects/org_development/issues/241
=> Notification icon

siteservice/website/components/login/views/loginsmsform.html, siteservice/website/components/login/views/logintotpform.html, siteservice/website/components/user/directives/authorizationDetails.html
Before:
After:
Closes https://github.com/gig-projects/org_development/issues/253
=> Authorization screen style improvements

siteservice/login.go, siteservice/service.go, siteservice/website/components/login/loginApp.js, siteservice/website/components/login/recoverAccountController.js, siteservice/website/components/login/views/forgotpassword.html, siteservice/website/components/login/views/resetpassword.html, siteservice/website/login.html
Part of https://github.com/gig-projects/org_development/issues/190
=> Reset password page

siteservice/website/assets/css/style.css, siteservice/website/base.html, siteservice/website/components/company/views/detail.html, siteservice/website/components/company/views/new.html, siteservice/website/components/organization/views/detail.html, siteservice/website/components/organization/views/new.html, siteservice/website/components/user/views/authorize.html, siteservice/website/components/user/views/home.html
Closes https://github.com/gig-projects/org_development/issues/249
=> Style improvements

siteservice/website/components/user/controller.js, siteservice/website/components/user/views/home.html
Part of https://github.com/gig-projects/org_development/issues/227
=> Immediately show a phonenumber as 'verified' if it's the same number as an already verified one

identityservice/user/users_api.go
UI will call the verify method explicitly instead
=> Do not send verification when changing or adding phonenumber

identityservice/user/users_api.go, siteservice/website/assets/css/style.css, siteservice/website/base.html, siteservice/website/components/app.js, siteservice/website/components/user/controller.js, siteservice/website/components/user/service.js, siteservice/website/components/user/views/phonenumberdialog.html, validate.sh
Closes https://github.com/gig-projects/org_development/issues/228
=> Show error/confirmation when updating or deleting last phone number

siteservice/website/assets/css/style.css, siteservice/website/base.html, siteservice/website/components/user/controller.js, siteservice/website/components/user/service.js, siteservice/website/components/user/views/emailaddressdialog.html, siteservice/website/components/user/views/home.html, siteservice/website/components/user/views/phonenumberdialog.html, siteservice/website/registration.html, specifications/api/users.raml
Closes https://github.com/gig-projects/org_development/issues/187
=> Email verification UI

siteservice/website/components/organization/controller.js, siteservice/website/components/user/controller.js, siteservice/website/components/user/service.js, siteservice/website/components/user/views/APIKeyDialog.html, siteservice/website/components/user/views/home.html
Closes https://github.com/gig-projects/org_development/issues/183
=> User api keys UI

db/user/Phonenumber.go, siteservice/website/components/registration/registrationResendSmsController.js, siteservice/website/components/registration/views/registrationresendsms.html, siteservice/website/components/user/service.js, siteservice/website/components/user/views/phonenumberdialog.html
Closes https://github.com/gig-projects/org_development/issues/297
=> Require the country code in phone number

format.sh, siteservice/service.go, siteservice/website/apidocumentation.html, siteservice/website/assets/css/style.css, siteservice/website/base.html, siteservice/website/components/user/views/home.html, siteservice/website/error.html, siteservice/website/index.html, siteservice/website/login.html, siteservice/website/registration.html, templates/email/emailvalidation.html, templates/email/emailwithbutton.html, templates/email/passwordreset.html, templates/templates.go, validation/email.go
Part of https://github.com/gig-projects/org_development/issues/187
=> Email verification

db/contract/Contract.go, db/contract/db.go, identityservice/contract/contracts_api.go, identityservice/contract/oauth2_oauth_2_0_middleware.go, identityservice/service.go
Make sure to remove index ContractId when updating.
=> Add contract signatures api

siteservice/website/base.html, siteservice/website/components/app.js, siteservice/website/components/login/loginApp.js, siteservice/website/components/user/UserDialogService.js, siteservice/website/components/user/authorizeController.js, siteservice/website/components/user/controller.js, siteservice/website/components/user/directives/authorizationDetails.html, siteservice/website/components/user/views/authorize.html, siteservice/website/login.html
Closes https://github.com/gig-projects/org_development/issues/252
=> Ability to create new phone numbers/emails/bank accounts/addresses on authorize page

db/company/Company.go, db/organization/Organization.go, db/user/Authorization_test.go, db/user/User.go, siteservice/login.go, siteservice/website/components/registration/views/registrationform.html, specifications/api/itsyouonline.raml
=> Do not allow capital cases in username and globalId

siteservice/website/components/organization/views/detail.html
Closes https://github.com/gig-projects/org_development/issues/207
=> Remove contracts tab

db/user/Address.go, db/user/Authorization.go, db/user/BankAccount.go, db/user/Phonenumber.go, db/user/User.go, db/user/db.go, db/validation/db.go, identityservice/user/users_api.go, identityservice/user/userview.go, milestones/1:0.9 alfa.md, siteservice/login.go, siteservice/registration.go, siteservice/website/components/user/UserDialogService.js, siteservice/website/components/user/authorizeController.js, siteservice/website/components/user/controller.js, siteservice/website/components/user/directives/authorizationDetails.html, siteservice/website/components/user/directives/authorizationDetailsDirective.js, siteservice/website/components/user/service.js, siteservice/website/components/user/views/addressdialog.html, siteservice/website/components/user/views/authorizationDialog.html, siteservice/website/components/user/views/bankAccountDialog.html, siteservice/website/components/user/views/emailaddressdialog.html, siteservice/website/components/user/views/home.html, siteservice/website/components/user/views/phonenumberdialog.html, siteservice/website/components/user/views/verifyPhoneDialog.html, specifications/api/itsyouonline.raml, validation/phonenumber.go
Closes https://github.com/gig-projects/org_development/issues/337
=> Raml 1.0 compliancy

siteservice/website/assets/css/style.css, siteservice/website/components/shared/directives/header.html, siteservice/website/components/user/controller.js, siteservice/website/components/user/views/home.html
=> Improve notification badge and add unread count to "notifications" tab label

siteservice/website/base.html, siteservice/website/components/organization/views/detail.html, siteservice/website/components/user/views/home.html
Closes https://github.com/gig-projects/org_development/issues/341
Closes #160 
Closes #162
=> Fix safari displaying an empty page

siteservice/website/assets/css/style.css, siteservice/website/components/user/controller.js, siteservice/website/components/user/views/home.html
Closes https://github.com/gig-projects/org_development/issues/361
=> Show notification when user has no verified email address

credentials/totp/db.go, db/validation/db.go, identityservice/user/users_api.go, identityservice/user/users_if.go, siteservice/login.go, siteservice/website/base.html, siteservice/website/components/app.js, siteservice/website/components/organization/views/apikeydialog.html, siteservice/website/components/organization/views/createOrganizationDialog.html, siteservice/website/components/organization/views/detail.html, siteservice/website/components/organization/views/dnsDialog.html, siteservice/website/components/organization/views/invitationdialog.html, siteservice/website/components/registration/views/registrationform.html, siteservice/website/components/user/controller.js, siteservice/website/components/user/service.js, siteservice/website/components/user/views/APIKeyDialog.html, siteservice/website/components/user/views/addressdialog.html, siteservice/website/components/user/views/authorizationDialog.html, siteservice/website/components/user/views/bankAccountDialog.html, siteservice/website/components/user/views/emailaddressdialog.html, siteservice/website/components/user/views/facebookDialog.html, siteservice/website/components/user/views/githubDialog.html, siteservice/website/components/user/views/home.html, siteservice/website/components/user/views/nameDialog.html, siteservice/website/components/user/views/phonenumberdialog.html, siteservice/website/components/user/views/resetPasswordDialog.html, siteservice/website/components/user/views/setupTOTPDialog.html, siteservice/website/components/user/views/verifyPhoneDialog.html, specifications/api/itsyouonline.raml
Previously this was only possible on the registration page.
Closes https://github.com/gig-projects/org_development/issues/360
=> Ability to add authenticator application as two-factor authentication method

siteservice/website/components/login/twoFactorAuthenticationController.js, siteservice/website/components/login/views/twoFactorAuthentication.html
=> Improve login flow

siteservice/website/components/user/views/APIKeyDialog.html
Part of https://github.com/gig-projects/org_development/issues/345
=> Show application id in API key dialog

db/validation/db.go
Use upsert instead of insert to prevent duplication error
=> Fix inserting of duplicate verification

db/user/DigitalAssetAddress.go, db/user/User.go, db/user/db.go, identityservice/user/user_api_digitalassetaddress.go, identityservice/user/users_if.go, specifications/api/itsyouonline.raml, templates/packaged/templates.go
=> Add crud for virtualcurrency

db/user/Authorization.go, docs/oauth2/availableScopes.md, siteservice/website/components/app.js, siteservice/website/components/user/UserDialogService.js, siteservice/website/components/user/authorizeController.js, siteservice/website/components/user/controller.js, siteservice/website/components/user/directives/authorizationDetails.html, siteservice/website/components/user/service.js, siteservice/website/components/user/views/digitalWalletAddressDialog.html, siteservice/website/components/user/views/home.html
Work in progress - do not merge
To do:
- Add ability to ask currency type in scope
- Probably create a list of valid currencies and let the user choose from that instead of letting the user supply it
Part of #185
=> UI for digital wallet

db/user/Authorization.go, db/user/User.go, docs/oauth2/availableScopes.md, identityservice/user/users_api.go, identityservice/user/userview.go, siteservice/website/components/app.js, siteservice/website/components/user/UserDialogService.js, siteservice/website/components/user/authorizeController.js, siteservice/website/components/user/controller.js, siteservice/website/components/user/directives/authorizationDetails.html, siteservice/website/components/user/directives/authorizationDetailsDirective.js, siteservice/website/components/user/service.js, siteservice/website/components/user/views/digitalWalletAddressDialog.html, siteservice/website/components/user/views/home.html
=> Digital wallet UI

docs/oauth2/oauth2.md, oauthservice/access_token.go
=> Add expire_at when returning access_token

siteservice/login.go, siteservice/website/components/login/recoverAccountController.js, validation/email.go
=> Fix password reset

communication/email.go
=> Send password reset email to all verified email addresses

docs/examples/thirdPartyService/dronedeliveryConsumer/droneDeliveryClient/client.py, docs/examples/thirdPartyService/dronedeliveryConsumer/droneDeliveryConsumer.py, docs/examples/thirdPartyService/dronedeliveryService/app.py, docs/examples/thirdPartyService/dronedeliveryService/deliveries.py, docs/examples/thirdPartyService/dronedeliveryService/index.html, docs/examples/thirdPartyService/guide.md
Finished example and documentation
=> Complete example with documentation

clients/go/itsyouonline/oauth.go
Login with credentials ported from python version https://github.com/itsyouonline/identityserver/blob/master/clients/python/itsyouonline/__init__.py#L12
jwt creation without scope tested on prod.
With scope tested on staging.
=> Add login with credentials + jwt creation.

docs/oauth2/oauth2.md
"read" is a non-existing/supported/available scope
=> Replace scope=read with scope=user:name

docs/oauth2/jwt.md
Remove the "aud=external" from the first HTTP request to create a JWT, and some minor formatting updates
=> Remove the "aud=external"

identityservice/user/user_api_digitalassetaddress.go, siteservice/service.go, siteservice/website/apidocumentation.html, siteservice/website/components/user/UserDialogService.js
Fix #269: digital wallet shows wrong info
Updated api documentation style
=> Fix #272: XSS in error page

oauthservice/access_token.go
See: https://tools.ietf.org/html/rfc6749#section-2.3.1
=> Make it possible to send client_id/client_secret as basic auth

oauthservice/jwt.go
- See discussion at :
https://auth0.com/forum/t/client-id-or-multiple-audiences-in-json-web-token/1289/2.
=> Remove client_id as default audiences.

db/organization/Organization.go, db/organization/OrganizationUser.go, db/validation/db.go, identityservice/invitations/JoinOrganizationInvitation.go, identityservice/organization/organizations_api.go, siteservice/website/components/organization/controller.js, siteservice/website/components/organization/views/changeRoleDialog.html, siteservice/website/components/organization/views/detailTabsPeople.html
Also refactors some methods so they execute faster
Closes #557
=> refactor(organization): Drop full name support to identify users

siteservice/website/components/see/see-detail.controller.js, siteservice/website/components/see/see-list.controller.js, siteservice/website/components/see/views/see-detail-page.html, siteservice/website/components/see/views/see-list-page.html, siteservice/website/components/user/UserDialogService.js, siteservice/website/components/user/authorizeController.js, siteservice/website/components/user/controller.js, siteservice/website/components/user/service.js, siteservice/website/components/user/views/authorizations.html, siteservice/website/components/user/views/notifications.html, siteservice/website/components/user/views/organizations.html, siteservice/website/components/user/views/profile.html, siteservice/website/components/user/views/settings.html
=> fix: Show full name or user identifier instead of username everywhere

specifications/api/itsyouonline.raml
Use Organization and JoinOrganizationInvitation instead since they are the same objects
Also remove MemberView that is no longer returned by the api
Closes #569
=> fix(apidoc): Remove OrganizationView and JoinOrganizationInvitationView from raml

siteservice/website/components/see/see-detail.controller.js
Seems like I made a mistake in one of the PRs
=> Move getting user identifier back to correct method

siteservice/website/assets/css/style.css, siteservice/website/components/login/loginController.js, siteservice/website/components/login/views/loginform.html, siteservice/website/components/organization/controller.js, siteservice/website/components/organization/views/detailTabsSettings.html, siteservice/website/components/organization/views/logoDialog.html, siteservice/website/components/registration/registrationController.js, siteservice/website/components/registration/views/registrationform.html
Get rid of `<canvas>` to render the logo and just render it using an ordinary `<img>` tag.
Closes #553
=> refactor(organization): Improve organization logo

siteservice/website/components/login/loginController.js
=> Trim username/email/password when submitting to server

.travis.yml, karma.conf.js
updated the travis file to fix some build issues
=> Fix travis jobs

siteservice/website/components/organization/views/apikeydialog.html
See: #717
Signed-off-by: Jo De Boeck <deboeck.jo@gmail.com>
=> Make it possible to select and copy secret

db/user/Authorization.go, docs/oauth2/oidc.md, oauthservice/access_token.go, oauthservice/oidc.go, oauthservice/oidc_test.go
=> Adds OpenID Connect support
